version: '3.8'

services:
  tomcat:
    image: tomcat:9.0
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./sample.war:/usr/local/tomcat/webapps/sample.war

  apache:
    image: httpd:2.4
    container_name: apache
    ports:
      - "80:80"
    depends_on:
      - tomcat
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
